# Site settings for GitHub Pages
title: "Weather Data Collector Spain"
description: "Comprehensive weather data collection and analysis for Spain using AEMET OpenData API"
url: "https://mosquito-alert.github.io"
baseurl: "/weather-data-collector-spain"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages specific settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: Mosquito Alert
twitter:
  username: mosquitoalert
social:
  name: Mosquito Alert
  links:
    - https://github.com/Mosquito-Alert

# Table of contents
kramdown:
  toc_levels: 1..3
  auto_ids: true

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
