# Site settings for GitHub Pages
title: "Weather Data Collector Spain"
description: "Comprehensive weather data collection and analysis for Spain using AEMET OpenData API"
url: "https://mosquito-alert.github.io"
baseurl: "/weather-data-collector-spain"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages specific settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# SEO settings
author: Mosquito Alert
twitter:
  username: mosquitoalert
social:
  name: Mosquito Alert
  links:
    - https://github.com/Mosquito-Alert

# Navigation
nav_links:
  - title: "Home"
    url: "/"
  - title: "API Analysis"
    url: "/api-analysis"
  - title: "Data Structure"
    url: "/data-structure"
  - title: "Scripts Documentation"
    url: "/scripts"
  - title: "Variable Reference"
    url: "/variables"

# Collections
collections:
  analysis:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
